### ISSUE TITLE
[SUGGESTION] PS2 NFS Games Support

### ISSUE THREAD

**Issue by ghost** [NFSTools/YAMLDatabase#18]
Hey. It would be nice to see PS2 support for Attribulator, as it would be a huge gamechanger. I know Carbon PS2 is there, but is there a chance we may see ProStreet and Undercover (PS2) being added to Attribulator so we can ditch VltEd 1.1/2.1 once and for all?

**Comment by LeoCodes21** [comment]
Probably not.

**Comment by ghost** [comment]
That's disappointing.
